Repository bdirs/bdirs-authentication, pull requests merged in 2019-08, with the labels that each got.

#5 #167538868: Integrate Code climate.
  .codeclimate.yml
  readme.md
Labels: reviewing

#13 #167511443: Setup Postgresql client.
  .gitignore
  .sequelizerc
  jest.config.js
  package.json
  src/app.ts
  src/db/config/config.ts
  src/db/models/index.ts
  tsconfig.json
Labels: working progress

#14 #167784021 Setup user model.
  src/db/migrations/20190809114736-create-user.js
  src/db/models/user.js
Labels: working progress

#15 chore(base): setup base classes
  .gitignore
  .sequelizerc
  .travis.yml
  package.json
  src/app.ts
  src/base/BaseController.ts
  src/base/BaseService.ts
  src/base/__mocks__/mockService.ts
  src/base/__tests__/BaseController.spec.ts
  src/base/__tests__/BaseService.spec.ts
  src/base/interfaces/IController.ts
  src/base/interfaces/IService.ts
  src/db/config/config.ts
  src/db/models/index.ts
  src/db/models/user.ts
  src/utils/HttpResponse.ts
  src/utils/__tests__/HttpResponse.spec.ts
  src/utils/index.ts
Labels: writing tests

#17 #167561011 Create super admin on startup
  package.json
  src/app.ts
  src/db/config/config.ts
  src/index.ts
  src/loaders/StartUpHelper.ts
  src/loaders/index.ts
  src/services/UserService.ts
  src/services/index.ts
  src/types/index.ts
  src/types/user.type.ts
Labels: writing tests
